anypoint :

  username: "jmf1104"
  password : "John000@"
  envid : "efde6aed-a767-4bc6-9469-34d6e10c0059"
  host : "anypoint.mulesoft.com"
  
http:

  port : "8081"  
  
file:

  path: ""  
  
elk:

   host : " " 
   host1 : " "
   
  
  
  